// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFzeRsiIgupThddT7kzoeL4sp1d30CSk',
    appId: '1:767061599228:web:9086b21ca96a8ea8658879',
    messagingSenderId: '767061599228',
    projectId: 'robikoshop-1df62',
    authDomain: 'robikoshop-1df62.firebaseapp.com',
    storageBucket: 'robikoshop-1df62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMZ_k9ew7nZ1E-3gAuMyEzI6weRn4KeAw',
    appId: '1:767061599228:android:385b2df861ce704d658879',
    messagingSenderId: '767061599228',
    projectId: 'robikoshop-1df62',
    storageBucket: 'robikoshop-1df62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfMn2Qk_tZ9GiC3-vHpk3Xp-QaJav4M3c',
    appId: '1:767061599228:ios:8e077d892178df17658879',
    messagingSenderId: '767061599228',
    projectId: 'robikoshop-1df62',
    storageBucket: 'robikoshop-1df62.appspot.com',
    iosBundleId: 'com.example.robikoShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfMn2Qk_tZ9GiC3-vHpk3Xp-QaJav4M3c',
    appId: '1:767061599228:ios:5ef4e9d818c8277c658879',
    messagingSenderId: '767061599228',
    projectId: 'robikoshop-1df62',
    storageBucket: 'robikoshop-1df62.appspot.com',
    iosBundleId: 'com.example.robikoShop.RunnerTests',
  );
}
